force-app/main/default/objects/Apex_Factory_Configuration__mdt/Apex_Factory_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used by Factory classes to instantiate concrete versions of interfaces based on the configured Apex class name.</description>
    <label>Apex Factory Configuration</label>
    <pluralLabel>Apex Factory Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Apex_Factory_Configuration__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <label>Apex Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Factory_Configuration__mdt/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <description>Used to query configurations by use case. Do not want to use a unique value such as DeveloperName to allow for test configurations. Can be the same value as DeveloperName.</description>
    <label>Configuration Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Factory_Configuration__mdt/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <description>Used to designate specific test cases. Leave blank for production use.</description>
    <inlineHelpText>Used to designate specific test cases. Leave blank for production use.</inlineHelpText>
    <label>Test Case</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfiguredPluginRegistry.cls
public inherited sharing class ConfiguredPluginRegistry extends PluginRegistry 
{
    @testVisible
    private static String testCase = '';

    public ConfiguredPluginRegistry() {
        super();
    }
    public ConfiguredPluginRegistry(Map<String, Plugin> cacheDefaults) {
        super(cacheDefaults);
    }

    override public Plugin lookup(String useCase) {
        try {
            if (!this.pluginCache.containsKey(useCase)) {
                loadConfiguration(useCase);
            }
            return this.pluginCache.get(useCase);
        }
        catch(Exception e) {
            throw new NotRegisteredException(new UseCase(useCase));
        }
    }

    private void loadConfiguration(String useCase) {
        this.reregister(
            useCase, 
            [SELECT 
                DeveloperName, 
                Apex_Class_Name__c 
                FROM Apex_Factory_Configuration__mdt 
                WHERE Configuration_Name__c = :useCase
                AND Test_Case__c = :testCase
            ].Apex_Class_Name__c
        );
    }
}